# version: '1'

services:
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    image: frontend-img:dev
    container_name: frontend_c
    ports:
      - "443:443"
    depends_on:
      - pong_service
    env_file: .env
    networks:
      - frontend-network
    restart: always
    volumes:
      - frontend-data:/app/frontend

  pong_service:
    build:
      context: ./services/backend/pong_service
      dockerfile: Dockerfile
    image: pong_service-img:dev
    container_name: game_service_c
    ports:
      - "8000:8000"
    env_file: .env
    restart: always
    depends_on:
      database:
        condition: service_healthy
    networks:
      - frontend-network
      - backend-network

  # user_service:
  #   build:
  #     context: ./services/backend/user_service
  #     dockerfile: Dockerfile
  #   image: user_service-img:dev
  #   container_name: user_service_c
  #   ports:
  #     - "8000:8000"
  #   env_file: .env
  #   restart: always
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   networks:
  #     - frontend-network
  #     - backend-network

  database:
    build:
      context: ./services/backend/database
      dockerfile: Dockerfile
    image: database-img:dev
    container_name: database_c
    ports:
      - "5432:5432"
    env_file: .env
    restart: always
    networks:
      - backend-network
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 3s
      timeout: 15s
      retries: 10

volumes:
  frontend-data:
    name: frontend-data
    driver: local
    driver_opts:
      type: none
      device: ./services/frontend/srcs
      o: bind
  database-data:
    name: database-data

networks:
  frontend-network:
    name: frontend-network
  backend-network:
    name: backend-network
