# version: '1'

services:
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    image: frontend-img:dev
    container_name: frontend
    ports:
      - "443:443"
    depends_on:
      - backend
    env_file: .env
    networks:
      - frontend-network
    restart: always
    volumes:
      - frontend-data:/app/frontend

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    image: backend-img:dev
    container_name: backend
    ports:
      - "8000:8000"
    env_file: .env
    restart: always
    depends_on:
      database:
        condition: service_healthy
    networks:
      - frontend-network
      - backend-network

  database:
    build:
      context: ./services/database
      dockerfile: Dockerfile
    image: database-img:dev
    container_name: database
    ports:
      - "5432:5432"
    env_file: .env
    restart: always
    networks:
      - backend-network
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 3s
      timeout: 15s
      retries: 10

volumes:
  frontend-data:
    name: frontend-data
  database-data:
    name: database-data

networks:
  frontend-network:
    name: frontend-network
  backend-network:
    name: backend-network
